import Header from "@/app/ui/header";
import Footer from "@/app/ui/footer";
import { Inter } from "next/font/google";
import StyledComponentsRegistry from "../lib/AntdRegistry";
import "./globals.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => (
  <html lang="en">
    <body style={{ minWidth: "1920px" }} className={inter.className}>
      <Header></Header>
      <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      <Footer></Footer>
    </body>
  </html>
);

export default RootLayout;
